server:
   contextPath: "/resource"
   port: 8082
   
logging:
  level:
    org.springframework.security: DEBUG
    
#configuration:
#  securityserver:
#    scheme: http
#    host: localhost
#    discoveryHost: localhost
#    port: 8081       

security:
#  ignored:
#    - /**/webjars/**"
#    - /**/images/**
#    - /**/static/**
#    - /**/swagger-ui.html
#    - /**/swagger-resources
#    - /**/configuration/**
#    - /**/v2/api-docs
#    - /proxy.stream
  user:
    name: guest
    password: guest123     
  oauth2:   
    client:
      accessTokenUri: http://localhost:8081/oauth-server/oauth/token
      userAuthorizationUri: http://localhost:8081/oauth-server/oauth/authorize
      #client-id: microshark
      #client-secret: 3opm8b
      client-id: yostark
      client-secret: jep817
    resource:
      user-info-uri:  http://localhost:8081/oauth-server/user/details
      token-info-uri: http://localhost:8081/oauth-server/oauth/check_token
